
export default [
  // super_admin
  {
    title: "الصفحة الرئيسية",
    icon: "home",
    to: "/SuperAdminHome",
    type: "super_admin",
    building_type: "منازل وشقق",
  },
  {
    title: "المجمعات",
    icon: "pie-chart",
    to: "/centers",
    type: "super_admin",
    building_type: "منازل وشقق",
  },
  {
    title: "الشكاوي",
    icon: "pie-chart",
    to: "/complain",
    type: "super_admin",
    building_type: "منازل وشقق",
  },
  {
    title: "معلومات عنا",
    icon: "pie-chart",
    to: "/AboutUsLamassu",
    type: "super_admin",
    building_type: "منازل وشقق",
  },
  // super_admin
  // admin
  {
    title: "الصفحة الرئيسية",
    icon: "home",
    to: "/Index",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "الحسابات",
    icon: "dollar-sign",
    href: "https://counting.myexperience.center/ownerBills",
    type: "admin",
    target: "_blank",
    building_type: "منازل وشقق",
  },
  {
    title: "نماذج شقق",
    icon: "home",
    to: "/admin-forms-Apartments",
    type: "admin",
    building_type: "شقق",
  },
  {
    title: "نماذج منازل",
    icon: "home",
    to: "/admin-forms",
    type: "admin",
    building_type: "منازل",
  },
  {
    title: "الملاك",
    icon: "users",
    to: "/admin-owners",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "زيارات الملاك",
    icon: "users",
    to: "/admin-visits",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    group: "",
    model: false,
    icon: "mdi-apps",
    title: "المبيعات",
    type: "admin",
    building_type: "منازل وشقق",
    children: [
      {
        title: "موظفين المبيعات",
        icon: "user",
        to: "admin-sells-employee",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "أستفسارات الزبائن",
        icon: "phone",
        to: "admin-call-center",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "أستماراة طلب حجز وحدة سكنية",
        icon: "pen-tool",
        to: "admin-application-form",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "أستماراة طلب موافقة",
        icon: "pen-tool",
        to: "admin-confirmations-form",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "طلبات وحدة سكنية",
        icon: "arrow-left",
        to: "admin-reservations",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "عقود المبيعات",
        icon: "arrow-left",
        to: "admin-get-salesContracts",
        type: "admin",
      building_type: "منازل وشقق",
      },
    ],
  },
  {
    title: "الأشعارات",
    icon: "bell",
    to: "/admin-notifications",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "المصارف",
    icon: "dollar-sign",
    to: "/admin-bank-accounts",
    type: "admin",
    name: "bankAccounts",
    building_type: "منازل وشقق",
  },
  {
    group: "",
    model: false,
    icon: "mdi-apps",
    title: "خدمات ما بعد البيع",
    type: "admin",
    building_type: "منازل وشقق",
    children: [
      {
        title: "موظفين الصيانة",
        icon: "award",
        to: "admin-maintenance-employee",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "حجوزات الخدمات",
        icon: "award",
        to: "admin-reservation-service",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "الخدمات",
        icon: "award",
        to: "admin-services",
        type: "admin",
        building_type: "منازل وشقق",
      },
      {
        title: "الوحدات السكنية",
        icon: "home",
        to: "admin-buying-offers",
        type: "admin",
        building_type: "منازل وشقق",
      },
    ],
  },
  {
    title: "الحراس",
    icon: "users",
    to: "/admin-guards",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "الموظفين",
    icon: "user",
    to: "/admin-employees",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "المستخدمين",
    icon: "users",
    to: "/users",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "الأعلانات",
    icon: "aperture",
    to: "/admin-postings",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "المميزات",
    icon: "codesandbox",
    to: "/admin-advantages",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "كيف سمع عنا",
    icon: "codesandbox",
    to: "/admin-how_u_hear_about_us",
    type: "admin",
    building_type: "منازل وشقق",
  },
  {
    title: "الشكاوي",
    icon: "codesandbox",
    to: "/admin-complain",
    type: "admin",
    building_type: "منازل وشقق",
  },
  // admin
  // assistance
  {
    title: "الصفحة الرئيسية",
    icon: "home",
    to: "/Index",
    type: "assistance",
    name: "home",
    building_type: "منازل وشقق",
  },
  {
    title: "نماذج شقق",
    icon: "home",
    to: "/admin-forms-Apartments",
    type: "assistance",
    name: "forms-Apartments",
    building_type: "شقق",
  },
  {
    title: "نماذج منازل",
    icon: "home",
    to: "/admin-forms",
    type: "assistance",
    name: "forms",
    building_type: "منازل",
  },
  {
    title: "الملاك",
    icon: "users",
    to: "/admin-owners",
    type: "assistance",
    name: "owners",
    building_type: "منازل وشقق",
  },
  {
    title: "زيارات الملاك",
    icon: "users",
    to: "/admin-visits",
    type: "assistance",
    name: "visits",
    building_type: "منازل وشقق",
  },
  {
    group: "",
    model: false,
    icon: "mdi-apps",
    title: "المبيعات",
    type: "assistance",
    name: "sales",
    building_type: "منازل وشقق",
    children: [
      {
        title: "موظفين المبيعات",
        icon: "user",
        to: "admin-sells-employee",
        type: "assistance",
        name: "sells-employee",
        building_type: "منازل وشقق",
      },
      {
        title: "أستفسارات الزبائن",
        icon: "phone",
        to: "admin-call-center",
        type: "assistance",
        name: "call-center",
        building_type: "منازل وشقق",
      },
      {
        title: "أستماراة طلب حجز وحدة سكنية",
        icon: "pen-tool",
        to: "admin-application-form",
        type: "assistance",
        name: "application-form",
        building_type: "منازل وشقق",
      },
      {
        title: "أستماراة طلب موافقة",
        icon: "pen-tool",
        to: "admin-confirmations-form",
        type: "assistance",
        name: "confirmations-form",
        building_type: "منازل وشقق",
      },
      {
        title: "طلبات وحدة سكنية",
        icon: "arrow-left",
        to: "admin-reservations",
        type: "assistance",
        name: "reservations",
        building_type: "منازل وشقق",
      },
      {
        title: "عقود المبيعات",
        icon: "arrow-left",
        to: "admin-get-salesContracts",
        type: "assistance",
      name: "salesContracts",
      building_type: "منازل وشقق",
      },
    ],
  },
  {
    title: "الأشعارات",
    icon: "bell",
    to: "/admin-notifications",
    type: "assistance",
    name: "notifications",
    building_type: "منازل وشقق",
  },
  {
    title: "المصارف",
    icon: "dollar-sign",
    to: "/admin-bank-accounts",
    type: "assistance",
    name: "bankAccounts",
    building_type: "منازل وشقق",
  },
  {
    group: "",
    model: false,
    icon: "mdi-apps",
    title: "خدمات ما بعد البيع",
    type: "assistance",
    name: "After-sales-service",
    building_type: "منازل وشقق",
    children: [
      {
        title: "موظفين الصيانة",
        icon: "award",
        to: "admin-maintenance-employee",
        type: "assistance",
        building_type: "منازل وشقق",
      },
      {
        title: "حجوزات الخدمات",
        icon: "award",
        to: "admin-reservation-service",
        type: "assistance",
        name: "reservation-service",
        building_type: "منازل وشقق",
      },
      {
        title: "الخدمات",
        icon: "award",
        to: "admin-services",
        type: "assistance",
        name: "services",
        building_type: "منازل وشقق",
      },
      {
        title: "الوحدات السكنية",
        icon: "home",
        to: "admin-buying-offers",
        type: "assistance",
        name: "buying-offers",
        building_type: "منازل وشقق",
      },
    ],
  },
  {
    title: "الحراس",
    icon: "users",
    to: "/admin-guards",
    type: "assistance",
    name: "guards",
    building_type: "منازل وشقق",
  },
  {
    title: "الموظفين",
    icon: "user",
    to: "/admin-employees",
    type: "assistance",
    name: "employees",
    building_type: "منازل وشقق",
  },
  {
    title: "الأعلانات",
    icon: "aperture",
    to: "/admin-postings",
    type: "assistance",
    name: "postings",
    building_type: "منازل وشقق",
  },
  {
    title: "المميزات",
    icon: "codesandbox",
    to: "/admin-advantages",
    type: "assistance",
    name: "advantages",
    building_type: "منازل وشقق",
  },
  {
    title: "كيف سمع عنا",
    icon: "codesandbox",
    to: "/admin-how_u_hear_about_us",
    type: "assistance",
    name: "how_u_hear_about_us",
    building_type: "منازل وشقق",
  },
  {
    title: "الشكاوي",
    icon: "codesandbox",
    to: "/admin-complain",
    type: "assistance",
    name: "complain",
    building_type: "منازل وشقق",
  },
  // assistance
];
