export default [
  // super_admin
  {
    title: "Home Page",
    to: { name: "super-admin-home" },
    type: "super_admin",
    icon: { icon: "mdi-home-outline" },
    building_type: "منازل وشقق",
  },
  {
    title: "Complexes",
    to: { name: "super-admin-show-complexes" },
    building_type: "منازل وشقق",
    type: "super_admin",
    icon: { icon: "mdi-office-building-outline" },
  },
  {
    title: "Complaints",
    to: { name: "super-admin-show-complaints" },
    building_type: "منازل وشقق",
    type: "super_admin",
    icon: { icon: "mdi-compare-horizontal" },
  },
  {
    title: "About us lamassu",
    to: { name: "super-admin-show-about-us-lamassu" },
    type: "super_admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-phone-dial" },
  },
  //super_admin

  //admin
  {
    title: "Home Page",
    to: { name: "admin-index" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Accounts",
    href: "https://counting.myexperience.center/ownerBills",
    type: "admin",
    target: "_blank",
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Apartment models",
    to: { name: "admin-show-apartment-models" },
    type: "admin",
    building_type: "شقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "House Models",
    to: { name: "admin-show-house-models" },
    type: "admin",
    building_type: "منازل",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Owners",
    to: { name: "admin-show-owners" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Owners' visits",
    to: { name: "admin-show-owners-visits" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: 'Sales',
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: 'mdi-file-document-outline' },
    children: [
      { title: 'Sales staff', to: 'admin-show-sales-staff' },
      { title: 'Queries', to: 'admin-show-queries' },
      { title: 'Customer attendance form', to: 'admin-show-customer-attendance-form' },
      { title: 'Residential Unit Booking Application Form', to: 'admin-show-application-form' },
      { title: 'Approval Request Form', to: 'admin-show-approval-request-form' },
      { title: 'Residential Unit Requests', to: 'admin-show-residential-unit-requests' },
      { title: 'Sales Contracts', to: 'admin-show-sales-contracts' },
    ],
  },
  {
    title: "Notifications",
    to: { name: "admin-show-notifications" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Banks",
    to: { name: "admin-show-banks" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: 'After-Sales Services',
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: 'mdi-file-document-outline' },
    children: [
      { title: 'Maintenance Staff', to: 'admin-show-maintenance-staff' },
      { title: 'Service Bookings', to: 'admin-show-service-bookings' },
      { title: 'Services', to: 'admin-show-services' },
      { title: 'Residential Units', to: 'admin-show-residential-units' },
    ],
  },
  {
    title: "Guards",
    to: { name: "admin-show-guards" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Staff",
    to: { name: "admin-show-staff" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Users",
    to: { name: "admin-show-users" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Advertisements",
    to: { name: "admin-show-advertisements" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Features",
    to: { name: "admin-show-features" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "How did you hear about u",
    to: { name: "admin-show-how-did-you-hear-about-us" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Complaints",
    to: { name: "admin-show-complaints" },
    type: "admin",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  //admin

  //assistance
  {
    title: "Home Page",
    to: { name: "admin-index" },
    type: "assistance",
    name: "home",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Apartment models",
    to: { name: "admin-show-apartment-models" },
    type: "assistance",
    name: "forms-Apartments",
    building_type: "شقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "House Models",
    to: { name: "admin-show-house-models" },
    type: "assistance",
    name: "forms",
    building_type: "منازل",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Owners",
    to: { name: "admin-show-owners" },
    type: "assistance",
    name: "owners",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Owners' visits",
    to: { name: "admin-show-owners-visits" },
    type: "assistance",
    name: "visits",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: 'Sales',
    type: "assistance",
    name: "sales",
    building_type: "منازل وشقق",
    icon: { icon: 'mdi-file-document-outline' },
    children: [
      { title: 'Sales staff', name: "sells-employee", to: 'admin-show-sales-staff' },
      { title: 'Queries', name: "inquiries", to: 'admin-show-queries' },
      { title: 'Customer attendance form', name: "call-center", to: 'admin-show-customer-attendance-form' },
      { title: 'Residential Unit Booking Application Form', name: "application-form", to: 'admin-show-application-form' },
      { title: 'Approval Request Form', name: "confirmations-form", to: 'admin-show-approval-request-form' },
      { title: 'Residential Unit Requests', name: "reservations", to: 'admin-show-residential-unit-requests' },
      { title: 'Sales Contracts', name: "salesContracts", to: 'admin-show-sales-contracts' },
    ],
  },
  {
    title: "Notifications",
    to: { name: "admin-show-notifications" },
    type: "assistance",
    name: "notifications",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Banks",
    to: { name: "admin-show-banks" },
    type: "assistance",
    name: "bankAccounts",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: 'After-Sales Services',
    type: "assistance",
    name: "After-sales-service",
    building_type: "منازل وشقق",
    icon: { icon: 'mdi-file-document-outline' },
    children: [
      { title: 'Maintenance Staff', to: 'admin-show-maintenance-staff' },
      { title: 'Service Bookings', name: "reservation-service", to: 'admin-show-service-bookings' },
      { title: 'Services', name: "services", to: 'admin-show-services' },
      { title: 'Residential Units', name: "buying-offers", to: 'admin-show-residential-units' },
    ],
  },
  {
    title: "Guards",
    to: { name: "admin-show-guards" },
    type: "assistance",
    name: "guards",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Staff",
    to: { name: "admin-show-staff" },
    type: "assistance",
    name: "employees",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Advertisements",
    to: { name: "admin-show-advertisements" },
    type: "assistance",
    name: "postings",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Features",
    to: { name: "admin-show-features" },
    type: "assistance",
    name: "advantages",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "How did you hear about u",
    to: { name: "admin-show-how-did-you-hear-about-us" },
    type: "assistance",
    name: "how_u_hear_about_us",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  {
    title: "Complaints",
    to: { name: "admin-show-complaints" },
    type: "assistance",
    name: "complain",
    building_type: "منازل وشقق",
    icon: { icon: "mdi-home-outline" },
  },
  //admin
];
